### ISSUE TITLE
Document service objects

### ISSUE THREAD

**Issue by janxious** [lessonly/lessonly.github.io#55]
Document #fail! and failure states for service objects

**Comment by stevegrossi** [comment]
Really, we need to update our docs on service objects in general, as the convention is now always to inherit from `Service` and define `initialize` and `perform` instance methods.

**Comment by stevegrossi** [comment]
Re this particular issue, as a seed for what we might add to the styleguide:

Services are assumed to be successful by default, and as such they will always return `true` for `#success?` If a service's responsibility is such that it's possible to fail, you can call `fail!`, which has the sole effect of making `success?` return `false` from that point on. If it makes sense, you should (though there is no convention around it yet—we want to see what grows organically) define something like an `errors` method or separate query methods for the different ways we want to handle failure (e.g. `#network_timeout?`) so consumers of the service can get more info about why it failed.

I kind of regret making `fail!` a bang-method, since by Ruby convention those raise exceptions and this doesn't. I'd like to suggest changing that to `fail`. We could have a `fail!` method which raised a generic `Service::Failure` exception but that doesn't feel right either. Most likely, when a service fails it will be due to some *other* object's exception (e.g. `ActiveRecord::RecordNotFound`). Anyway, I think errors in services is still very much open to doscussion and improvement.

**Comment by armilam** [comment]
> the convention is now always to inherit from `Service` and define `initialize` and `perform` instance methods.

A new update: we inherit from `Service` and define *only* `perform`, as `Service` takes care of `initialize`.

**Comment by stevegrossi** [comment]
Are you thinking of jobs, @armilam? Our `Service` base class doesn't define `#initialize`; its children do in order to convert args to instance variables, and they all also define a zero-arity `#perform` method.

Sidekiq jobs work as you say: where all the arguments go to `#perform` rather than `#initialize`.

**Comment by armilam** [comment]
Whoops, my bad. Redacted.

**Comment by stevegrossi** [comment]
We should also mention our generator for serivces: `rails g service DoAThing`
